"""add indexes and constraints

Revision ID: c8a5d479601e
Revises: 649ebca125a4
Create Date: 2026-04-08 23:32:06.183270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a5d479601e'
down_revision: Union[str, Sequence[str], None] = '649ebca125a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_member', 'project_members', ['project_id', 'user_id'])
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.alter_column('task_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('todo', 'in_progress', 'done', 'blocked', name='taskstatus'),
               existing_nullable=False,
               postgresql_using='status::taskstatus')
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_logs_user_id'), 'task_logs', ['user_id'], unique=False)
    op.alter_column('tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.alter_column('tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_task_logs_user_id'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.alter_column('task_logs', 'status',
               existing_type=sa.Enum('todo', 'in_progress', 'done', 'blocked', name='taskstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_constraint('uq_project_member', 'project_members', type_='unique')
    # ### end Alembic commands ###
